// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDg4hKA1a5yWpnL2Zw8ACLWJ4ak7CX_b8M',
    appId: '1:579607775294:android:5e190a2ad13a351010e96f',
    messagingSenderId: '579607775294',
    projectId: 'employee-management-64732',
    storageBucket: 'employee-management-64732.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCLQLXw-PAG_njzgBUrt2EezXKXzOPwGZQ',
    appId: '1:579607775294:ios:9e4e25b896c9a27110e96f',
    messagingSenderId: '579607775294',
    projectId: 'employee-management-64732',
    storageBucket: 'employee-management-64732.firebasestorage.app',
    iosBundleId: 'com.example.empManagementProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCPSZoNsBvUm1rrcJwhPp8rlDlPEnp-9Oo',
    appId: '1:579607775294:web:e4fcf9a7eed06a1110e96f',
    messagingSenderId: '579607775294',
    projectId: 'employee-management-64732',
    authDomain: 'employee-management-64732.firebaseapp.com',
    storageBucket: 'employee-management-64732.firebasestorage.app',
  );
}
